version: '3'
services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
    command: bash -c "npm run migrate && npm run start"
    volumes:
      - static-content:/static
      - //var/run/docker.sock:/var/run/docker.sock
      - /combined.log:/combined.log
      - /error.log:/error.log

    ports:
      - 6069:3000
    networks:
      - alertly-network
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=alertly
      - PORT=3000
      - JWT_SECRET=AlertlySecret
      - JWT_ALGO=HS256
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - NODE_ENV=${NODE_ENV}
  postgres:
    image: postgres
    restart: unless-stopped
    # command: --init-file /data/application/init.sql
    volumes:
      - postgres-volume:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=alertly
    networks:
      - alertly-network
    # ports:
    #   - 5432:5432
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5432"]
    #   timeout: 5s
  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - '6070:8081'
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/alertly?sslmode=disable
    networks:
      - alertly-network
    depends_on:
      - postgres
volumes:
  postgres-volume:
    driver: local
  static-content:
    driver: local

networks:
  alertly-network:
