name: docs

on:
  schedule:
    - cron: "0 */6 * * *" # Called every 6 hours
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install App Dependencies
        run: cd generate-docs && npm install

      - name: Generate Docs
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
        run: |
          cd generate-docs && npm run generate
          cat temp-data.md > ../README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add README.md

          changes=$(git diff --cached)

          if [ -n "$changes" ]; then
              echo "Changes detected, committing"
              git commit -m "Update README.md from Notion (CICD)"
              git push
          fi
