name: releases
on:
  push:
    branches:
      - workflow-testing

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action Backend
        id: changelog-backend
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: ./backend/package.json
          git-path: ./backend

      - name: Get Android Build Version
        id: android-build-version
        run: |
          VERSION=$(grep 'versionName = ' android_client/app/build.gradle.kts | awk -F '"' '{print $2}')
          echo "Current Gradle Version: $VERSION"
          echo "export CURRENT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Conventional Changelog Action Android
        id: changelog-android
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-path: ./android_client
          pre-commit: ./.github/workflows/pre-commit-android.js
          skip-version-file: true

      - name: Update Android Build Gradle Version
        run: |
          echo ${{steps.changelog-android.outputs.tag}}
          sed -i "s/\(versionName = \)\"[^\"]*\"/\1\"${{steps.changelog-android.outputs.tag}}\"/" android_client/app/build.gradle.kts

      - name: create release backend
        uses: actions/create-release@v1
        if: steps.changelog-backend.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.changelog-backend.outputs.tag }}
          release_name: ${{ steps.changelog-backend.outputs.tag }}
          body: ${{ steps.changelog-backend.outputs.clean_changelog }}

      - name: create release android client
        uses: actions/create-release@v1
        if: steps.changelog-android.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.changelog-android.outputs.tag }}
          release_name: ${{ steps.changelog-android.outputs.tag }}
          body: ${{ steps.changelog-android.outputs.clean_changelog }}
