name: releases
on:
  push:
    branches:
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action Backend
        id: changelog-backend
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-path: ./backend
          version-file: ./backend/package.json

      - name: create release backend
        uses: actions/create-release@v1
        if: steps.changelog-backend.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.changelog-backend.outputs.tag }}
          release_name: ${{ steps.changelog-backend.outputs.tag }}
          body: ${{ steps.changelog-backend.outputs.clean_changelog }}

      - name: Conventional Changelog Action Android
        id: changelog-android
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-path: ./android_client
          skip-version-file: true

      - name: create release android
        uses: actions/create-release@v1
        if: steps.changelog-android.outputs.skipped == 'false'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ steps.changelog-android.outputs.tag }}
          release_name: ${{ steps.changelog-android.outputs.tag }}
          body: ${{ steps.changelog-android.outputs.clean_changelog }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        if: steps.changelog-backend.outputs.skipped == 'false'
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: cd Documents/Alertly/backend/ && bash start.sh
